language: objective-c
osx_image: xcode10.2
sudo: false

env:
  global:
    - PROJECT="MakeProjectTest.xcodeproj"
    - SDK="iphonesimulator12.2"
    - DESTINATION="platform=iOS Simulator,name=iPhone XS,OS=12.2"
  matrix:
    - SCHEME="MakeProjectTest"

